CE Attachments merge
CombatExtended-Continued/CombatExtendedArmory pull request #72
Opened 2024-01-18 08:05 UTC by SamaelGray

## Additions

- What it says on the tin, the content from Attachments merged into Armory now that the UBGL system is fixed.

## Changes

- Minor recipe typo fix.

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors

2024-03-25 21:05 UTC, SerinaCE reviewed
Would drop TP-82 and DoubleBadger too becaue useless, waiting for bossman on this

2024-04-18 22:45 UTC, N7Huntsman requested changes
Some remarks:
- As we discussed, split-off the Attachment merger stuff. It's its own discussion to be had, and having it in this PR is going going to slow down getting the necessary 1.5 update stuff. 
- For the LeMat:
  - It is a .44 caliber powder-and-ball revolver that was later converted to a pin-fire available in a 11 or 12mm cartridge. While I agree .44 magnum is more powerful side of things, the original gun is old enough we don't have great ammo options; we can either find an existing ammoset that's close and handwave that it was converted, or come up with a new one (mind, our current musket ball (slow) ammo is stat'd as .62 caliber).
  - Should probably increase the LeMat's reload time per round (and maybe make it load one at a time?)

2024-04-19 07:58 UTC, SamaelGray commented
The Attachments merge is reverted. The main problem with the LeMat is its texture which is the old cap and ball variants instead of the cartridge one, that's the part that makes the .44 mag situation worse.

2024-05-17 04:05 UTC, Airomeda commented
referencing from this PR on main mod https://github.com/CombatExtended-Continued/CombatExtended/pull/3135#issuecomment-2109894935, I think we need to add **CompProperties_Stunnable** to the shotgun turret.

2024-05-17 07:45 UTC, SamaelGray commented
Should already be known https://github.com/CombatExtended-Continued/CombatExtended/issues/3024#issuecomment-2051335559

2024-05-17 07:45 UTC, SamaelGray commented
> referencing from this PR on main mod [CombatExtended-Continued/CombatExtended#3135 (comment)](https://github.com/CombatExtended-Continued/CombatExtended/pull/3135#issuecomment-2109894935), I think we need to add `CompProperties_Stunnable` to the shotgun turret via the parent `TurretAutoBase` from main.

Should already be known https://github.com/CombatExtended-Continued/CombatExtended/issues/3024#issuecomment-2051335559

2024-05-31 12:26 UTC, Airomeda commented on 1.5/Defs/ThingDefs/Apparel_CEA/HeavyCompositeHelmet.xml
> +		</thingCategories>
redundant if ParentName is changed to `ArmorHelmetMakeableBase`

2024-06-27 05:15 UTC, N7Huntsman approved these changes

2024-06-27 05:15 UTC, merged